# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a568a29ec20e233077c4551e682d812f5f60d60ed872fd19587e956cf2995c70c638bfbc49fe6d6162bf4418a18cf8e6affb01c1b7b00d684c0e10ffbbe3a789

test:
  secret_key_base: 4f54cd2f5c5336f4e309ef6ff1bc4e68bf7beea4cfcd697428efd0ea18dfe23153872befe51364c3fef1fe2be007f09b5f8ced876b6c4e43dd9234a8eaf895b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
